// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QabilHire.Infrastructure.Persistence;

#nullable disable

namespace QabilHire.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260821150000_AddJobMatches")]
partial class AddJobMatches
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("QabilHire.Domain.Entities.JobMatch", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.Property<string>("TargetJobTitle").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
            b.Property<string>("Company").HasMaxLength(160).HasColumnType("character varying(160)");
            b.Property<string>("JobDescription").IsRequired().HasColumnType("text");
            b.Property<int>("OverallScore").HasColumnType("integer");
            b.Property<string>("MatchLevel").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
            b.Property<int>("TechnicalScore").HasColumnType("integer");
            b.Property<int>("ExperienceScore").HasColumnType("integer");
            b.Property<int>("EducationScore").HasColumnType("integer");
            b.Property<int>("ToolsScore").HasColumnType("integer");
            b.Property<int>("SoftSkillsScore").HasColumnType("integer");
            b.Property<string>("MatchedSkillsJson").IsRequired().HasColumnType("jsonb");
            b.Property<string>("MatchedStrengthsJson").IsRequired().HasColumnType("jsonb");
            b.Property<string>("GapsJson").IsRequired().HasColumnType("jsonb");
            b.Property<string>("PrioritiesJson").IsRequired().HasColumnType("jsonb");
            b.Property<string>("LikelyQuestionsJson").IsRequired().HasColumnType("jsonb");
            b.Property<string>("Summary").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
            b.Property<string>("RecommendedNextStep").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("UserId");
            b.ToTable("JobMatches");
        });
#pragma warning restore 612, 618
    }
}
